### ISSUE TITLE
ft_rrange.c

### ISSUE THREAD

**Issue by TigranMn** [pasqualerossi/42-School-Exam-Rank-02#28]
when end is smaller than start, your function returns array that contains ints from start to end, but shouldn't it  return from end to start? In example of subject ft_rrange(0, -3) should return {-3 , -2, -1 , 0}, but it returns {0, -1, -2, -3}.

**Comment by pasqualerossi** [comment]
Rewrite the function and I can add it in the repo.

**Comment by TigranMn** [comment]
> Rewrite the function and I can add it in the repo.

I have rewritten the function, but i don't have access to push and open PR
