### ISSUE TITLE
Diffrent type cast in function

### ISSUE THREAD

**Issue by C4rrelo** [pasqualerossi/42-School-Exam-Rank-02#34]
Hi, in level 2 the max function, you are using type cast (int) in result;

I Didn't pass in the exam because of that, it wont work, moullinete wont pass.

Switch (int) type cast in Result to Unsigned int, and it will pass.

**Comment by pasqualerossi** [comment]
can you please rewrite the code and I'll add it to the repo.

**Comment by C4rrelo** [comment]
int max( int *tab, unsigned int len)
{
	unsigned int result;
	unsigned int i = 0;
	result = tab[i];
	
	while(i < len)
	{
		if (result <  tab[i])
		{
			result = tab[i];
		}
		i++;
	}
	return(result);
}

**Comment by C4rrelo** [comment]
I cant send a .c file so i send in .txt

[max.txt](https://github.com/pasqualerossi/42-School-Exam-Rank-02/files/11456393/max.txt)

**Comment by C4rrelo** [comment]
I cant send a .c file so its going in .txt

[max.txt](https://github.com/pasqualerossi/42-School-Exam-Rank-02/files/11456399/max.txt)
