### ISSUE TITLE
Else condition after while

### ISSUE THREAD

**Issue by PedroVMota** [pasqualerossi/42-School-Exam-Rank-02#36]
```
while(...)
    ....
 else
 {
    res[i] = start;
    start--;
    i++;
 }
 
```
 You have a "else" after a while. In my knowledge that is a syntax error

**Comment by pasqualerossi** [comment]
what should the code look like, I'll update it.

**Comment by PedroVMota** [comment]
`
int     *ft_range(int start, int end)
{
	int i = 0;
  	int len = abs((end - start)) + 1;
  	int *res; 
  	res = (int *)malloc(sizeof(int) * len);
  
  	while (i < len)
  	{
    	  if (start < end)
    	  {
		  res[i] = start;
		  start++;
    		  i++;
          }
		  else
  			{
    			res[i] = start;
    			start--;
    			i++;
  			}
	}
  	return (res);
}
`
Something like this

**Comment by pasqualerossi** [comment]
Thanks Pedro, I'll update it now.
