### ISSUE TITLE
rosting doesnt work with ./a.out "abc def "

### ISSUE THREAD

**Issue by B18a** [pasqualerossi/42-School-Exam-Rank-02#51]
when testing the programm with 

```
./a.out "abc def "
```

the result is

`abf  abc$`

with 2 spaces in betweeen. unfortunately i didnt find a solution for that in your code.

**Comment by axcel1403** [comment]
> when testing the programm with
> 
> ```
> ./a.out "abc def "
> ```
> 
> the result is
> 
> `abf abc$`
> 
> with 2 spaces in betweeen. unfortunately i didnt find a solution for that in your code.

Actually, the code doesn't work with those 4 tests:

 ```
./a.out "abc test" | cat -e
testabc$
./a.out "abc test " | cat -e
test  abc$
./a.out " abc test" | cat -e
testabc$
./a.out " abc test " | cat -e
test  abc$
 ```
