### ISSUE TITLE
ft_range

### ISSUE THREAD

**Issue by ManuCiao10** [pasqualerossi/42-School-Exam-Rank-02#7]
-ft_range dosn't work. 
-When start = 0 and end = [-negative number]

<img width="479" alt="Screenshot 2022-08-12 at 15 35 06" src="https://user-images.githubusercontent.com/89024276/184430646-c85654be-024c-4ec3-a3e8-66ecf73d09bb.png">

**Comment by Laendrun** [comment]
I can also note that when the ```end``` and ```size``` are 0 we have to return an array containing one int that is ```0```, in this example, when size is 0, the code only returns ```NULL```
