### ISSUE TITLE
Union warnings

### ISSUE THREAD

**Issue by veloxity343** [pasqualerossi/42-School-Exam-Rank-02#76]
The array "seen" needs to be of type unsigned char to match the range of possible values for warning flags enabled in compilation

**Comment by veloxity343** [comment]
#include <unistd.h>

int main(int ac, char **av)
{
    if (ac == 3)
    {
        unsigned char seen[256] = {0};
        int i = 0;
        int j = 0;

        while (av[1][i])
        {
            if (!seen[(unsigned char)av[1][i]])
            {
                write(1, &av[1][i], 1);
                seen[(unsigned char)av[1][i]] = 1;
            }
            i++;
        }
        while (av[2][j])
        {
            if (!seen[(unsigned char)av[2][j]])
            {
                write(1, &av[2][j], 1);
                seen[(unsigned char)av[2][j]] = 1;
            }
            j++;
        }
    }
    write(1, "\n", 1);
    return 0;
}

**Comment by pasqualerossi** [comment]
create a pull request and I'll update it. Thanks!

**Comment by amema42** [comment]
yeah, that's right! also a cast to unsigned char ensures the character is within the 0-255 range inside the while loops for the if conditions and the seen variable :)

I'll create a pull request

**Comment by veloxity343** [comment]
> yeah, that's right! also a cast to unsigned char ensures the character is within the 0-255 range inside the while loops for the if conditions and the seen variable :)
> 
> 
> 
> I'll create a pull request

Hi, I'm not too sure how comments work in GitHub so I hope I'm doing this right. Just wanted to ask, why must the while loops have a cast to unsigned char for "seen" when it has already been defined in the declaration and init?

**Comment by amema42** [comment]
> > yeah, that's right! also a cast to unsigned char ensures the character is within the 0-255 range inside the while loops for the if conditions and the seen variable :)
> > I'll create a pull request
> 
> Hi, I'm not too sure how comments work in GitHub so I hope I'm doing this right. Just wanted to ask, why must the while loops have a cast to unsigned char for "seen" when it has already been defined in the declaration and init?

hey there! So

as u probably know, in C, the `char` type can be either signed or unsigned, depending on the platform and compiler settings - this means that signed characters can have negative values, while unsigned characters range from 0 to 255. For our purposes, we need the values from the ASCII table, which are strictly positive: 0-127 for standard ASCII and 0-255 for extended ASCII. Using a character as an index for an array, if the character is signed and has a negative value, it could lead to out-of-bounds access, resulting in undesirable behavior or runtime errors etc. To ensure that characters are always treated as non-negative values, it is necessary to cast them to `unsigned char` within the `while` loops. This cast ensures that the character value is within the 0 to 255 range, thereby preventing possible out-of-bounds access and ensuring that the array is indexed correctly and safely. In other words, (sorry I'm being very repetitive && annoying hahah) casting to `unsigned char` normalizes the character values, ensuring they are always valid as indices for the `seen` array, regardless of their original sign. 

additionally, if the `seen` array is of type `int` or `unsigned char` and we are only dealing with valid ASCII characters (which are non-negative), this explicit casting might not be strictly necessary...the exercise will pass on the Moulinette without the casting; but yeah...however, including the casting makes the code much safer and more robust

**Comment by veloxity343** [comment]
> > > yeah, that's right! also a cast to unsigned char ensures the character is within the 0-255 range inside the while loops for the if conditions and the seen variable :)
> 
> > > I'll create a pull request
> 
> > 
> 
> > Hi, I'm not too sure how comments work in GitHub so I hope I'm doing this right. Just wanted to ask, why must the while loops have a cast to unsigned char for "seen" when it has already been defined in the declaration and init?
> 
> 
> 
> hey there! So
> 
> 
> 
> as u probably know, in C, the `char` type can be either signed or unsigned, depending on the platform and compiler settings - this means that signed characters can have negative values, while unsigned characters range from 0 to 255. For our purposes, we need the values from the ASCII table, which are strictly positive: 0-127 for standard ASCII and 0-255 for extended ASCII. Using a character as an index for an array, if the character is signed and has a negative value, it could lead to out-of-bounds access, resulting in undesirable behavior or runtime errors etc. To ensure that characters are always treated as non-negative values, it is necessary to cast them to `unsigned char` within the `while` loops. This cast ensures that the character value is within the 0 to 255 range, thereby preventing possible out-of-bounds access and ensuring that the array is indexed correctly and safely. In other words, (sorry I'm being very repetitive && annoying hahah) casting to `unsigned char` normalizes the character values, ensuring they are always valid as indices for the `seen` array, regardless of their original sign. 
> 
> 
> 
> additionally, if the `seen` array is of type `int` or `unsigned char` and we are only dealing with valid ASCII characters (which are non-negative), this explicit casting might not be strictly necessary...the exercise will pass on the Moulinette without the casting; but yeah...however, including the casting makes the code much safer and more robust

Thanks very much for that explanation! Take an honorary eval point on the house!❤️
