### ISSUE TITLE
You cant do that

### ISSUE THREAD

**Issue by AdrianG1911** [pasqualerossi/42-School-Exam-Rank-02#85]
https://github.com/pasqualerossi/42-School-Exam-Rank-02/blob/e3b23535927ac6d8901925495a90434b72508a55/Level%204/ft_itoa/ft_itoa.c#L7

You returned a non malloced string. In the problem's question it says that the returned array needs to be allocated. I have a fully working solution here, you can use it or take some inspiration:

```c
#include <stdlib.h>

int nlen(int nbr)
{
	int i;

	if (nbr == 0)
		return (1);
	i = 0;
	while (nbr != 0)
	{
		nbr /= 10;
		i++;
	}
	return (i);
}

int ft_abs(int nbr)
{
	if (nbr < 0)
		return (-nbr);
	return (nbr);
}

char	*ft_itoa(int nbr)
{
	char *cnum;
	int len;
	int i;

	len = nlen(nbr);
	i = 0;
	if (nbr < 0)
		i++;
	len = len + i;
	cnum = (char *)malloc((len + 1) * sizeof(char));
	if (!cnum)
		return (NULL);
	cnum[0] = '-';
	cnum[len] = '\0';
	while ((len - 1) >= i)
	{
		cnum[len - 1] = ft_abs(nbr % 10) + '0';
		nbr /= 10;
		len--;
	}
	return (cnum);
}
```

**Comment by pasqualerossi** [comment]
create a pull request and I’ll add your code in.

**Comment by MilosM1998** [comment]
You can just add :
if(nbr = -2147483648)
         return(ft_strdup("-2147483648"));

**Comment by AdrianG1911** [comment]
> You can just add : if(nbr = -2147483648) return(ft_strdup("-2147483648"));

Very true, though you need to write the ft_strdup function in that case.

**Comment by AdrianG1911** [comment]
> You can just add : if(nbr = -2147483648) return(ft_strdup("-2147483648"));

You need to write the code for ft_strdup, this is a test

**Comment by AdrianG1911** [comment]
> create a pull request and I’ll add your code in.

I created the pull request, thank you!
